package com.bean.model;

import java.io.Serializable;
import java.util.Date;

public class DbBirdexpresstype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdexpresstype.SID
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdexpresstype.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdexpresstype.SPECIALTYPE
     *
     * @mbg.generated
     */
    private String specialtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdexpresstype.OPERTIME
     *
     * @mbg.generated
     */
    private Date opertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_birdexpresstype
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdexpresstype.SID
     *
     * @return the value of db_birdexpresstype.SID
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdexpresstype.SID
     *
     * @param sid the value for db_birdexpresstype.SID
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdexpresstype.NAME
     *
     * @return the value of db_birdexpresstype.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdexpresstype.NAME
     *
     * @param name the value for db_birdexpresstype.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdexpresstype.SPECIALTYPE
     *
     * @return the value of db_birdexpresstype.SPECIALTYPE
     *
     * @mbg.generated
     */
    public String getSpecialtype() {
        return specialtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdexpresstype.SPECIALTYPE
     *
     * @param specialtype the value for db_birdexpresstype.SPECIALTYPE
     *
     * @mbg.generated
     */
    public void setSpecialtype(String specialtype) {
        this.specialtype = specialtype == null ? null : specialtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdexpresstype.OPERTIME
     *
     * @return the value of db_birdexpresstype.OPERTIME
     *
     * @mbg.generated
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdexpresstype.OPERTIME
     *
     * @param opertime the value for db_birdexpresstype.OPERTIME
     *
     * @mbg.generated
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdexpresstype
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbBirdexpresstype other = (DbBirdexpresstype) that;
        return (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSpecialtype() == null ? other.getSpecialtype() == null : this.getSpecialtype().equals(other.getSpecialtype()))
            && (this.getOpertime() == null ? other.getOpertime() == null : this.getOpertime().equals(other.getOpertime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdexpresstype
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSpecialtype() == null) ? 0 : getSpecialtype().hashCode());
        result = prime * result + ((getOpertime() == null) ? 0 : getOpertime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdexpresstype
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", name=").append(name);
        sb.append(", specialtype=").append(specialtype);
        sb.append(", opertime=").append(opertime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}