package com.bean.model;

import java.io.Serializable;

public class DbBirdproduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdproduct.SID
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdproduct.BIRDNAME
     *
     * @mbg.generated
     */
    private String birdname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdproduct.MABANGSKU
     *
     * @mbg.generated
     */
    private String mabangsku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdproduct.BIRDSKU
     *
     * @mbg.generated
     */
    private String birdsku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdproduct.MABANGNAME
     *
     * @mbg.generated
     */
    private String mabangname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_birdproduct.DESCR
     *
     * @mbg.generated
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_birdproduct
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdproduct.SID
     *
     * @return the value of db_birdproduct.SID
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdproduct.SID
     *
     * @param sid the value for db_birdproduct.SID
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdproduct.BIRDNAME
     *
     * @return the value of db_birdproduct.BIRDNAME
     *
     * @mbg.generated
     */
    public String getBirdname() {
        return birdname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdproduct.BIRDNAME
     *
     * @param birdname the value for db_birdproduct.BIRDNAME
     *
     * @mbg.generated
     */
    public void setBirdname(String birdname) {
        this.birdname = birdname == null ? null : birdname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdproduct.MABANGSKU
     *
     * @return the value of db_birdproduct.MABANGSKU
     *
     * @mbg.generated
     */
    public String getMabangsku() {
        return mabangsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdproduct.MABANGSKU
     *
     * @param mabangsku the value for db_birdproduct.MABANGSKU
     *
     * @mbg.generated
     */
    public void setMabangsku(String mabangsku) {
        this.mabangsku = mabangsku == null ? null : mabangsku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdproduct.BIRDSKU
     *
     * @return the value of db_birdproduct.BIRDSKU
     *
     * @mbg.generated
     */
    public String getBirdsku() {
        return birdsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdproduct.BIRDSKU
     *
     * @param birdsku the value for db_birdproduct.BIRDSKU
     *
     * @mbg.generated
     */
    public void setBirdsku(String birdsku) {
        this.birdsku = birdsku == null ? null : birdsku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdproduct.MABANGNAME
     *
     * @return the value of db_birdproduct.MABANGNAME
     *
     * @mbg.generated
     */
    public String getMabangname() {
        return mabangname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdproduct.MABANGNAME
     *
     * @param mabangname the value for db_birdproduct.MABANGNAME
     *
     * @mbg.generated
     */
    public void setMabangname(String mabangname) {
        this.mabangname = mabangname == null ? null : mabangname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_birdproduct.DESCR
     *
     * @return the value of db_birdproduct.DESCR
     *
     * @mbg.generated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_birdproduct.DESCR
     *
     * @param descr the value for db_birdproduct.DESCR
     *
     * @mbg.generated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdproduct
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbBirdproduct other = (DbBirdproduct) that;
        return (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
            && (this.getBirdname() == null ? other.getBirdname() == null : this.getBirdname().equals(other.getBirdname()))
            && (this.getMabangsku() == null ? other.getMabangsku() == null : this.getMabangsku().equals(other.getMabangsku()))
            && (this.getBirdsku() == null ? other.getBirdsku() == null : this.getBirdsku().equals(other.getBirdsku()))
            && (this.getMabangname() == null ? other.getMabangname() == null : this.getMabangname().equals(other.getMabangname()))
            && (this.getDescr() == null ? other.getDescr() == null : this.getDescr().equals(other.getDescr()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdproduct
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getBirdname() == null) ? 0 : getBirdname().hashCode());
        result = prime * result + ((getMabangsku() == null) ? 0 : getMabangsku().hashCode());
        result = prime * result + ((getBirdsku() == null) ? 0 : getBirdsku().hashCode());
        result = prime * result + ((getMabangname() == null) ? 0 : getMabangname().hashCode());
        result = prime * result + ((getDescr() == null) ? 0 : getDescr().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdproduct
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", birdname=").append(birdname);
        sb.append(", mabangsku=").append(mabangsku);
        sb.append(", birdsku=").append(birdsku);
        sb.append(", mabangname=").append(mabangname);
        sb.append(", descr=").append(descr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}