package com.bean.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DbCkyuser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.SID
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.EXPRESSID
     *
     * @mbg.generated
     */
    private String expressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.TOKENID
     *
     * @mbg.generated
     */
    private String tokenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.USERKEY
     *
     * @mbg.generated
     */
    private String userkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.CUSTOMUSERKEY
     *
     * @mbg.generated
     */
    private String customuserkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.OPER
     *
     * @mbg.generated
     */
    private String oper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.OPERTIME
     *
     * @mbg.generated
     */
    private Date opertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.FLAG
     *
     * @mbg.generated
     */
    private BigDecimal flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.OPENFLAG
     *
     * @mbg.generated
     */
    private BigDecimal openflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.CORPID
     *
     * @mbg.generated
     */
    private String corpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.TYPEID
     *
     * @mbg.generated
     */
    private String typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.TYPENAME
     *
     * @mbg.generated
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.TYPECOUNTRY
     *
     * @mbg.generated
     */
    private String typecountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.RESERVE1
     *
     * @mbg.generated
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.RESERVE2
     *
     * @mbg.generated
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.RESERVE3
     *
     * @mbg.generated
     */
    private String reserve3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.RESERVE4
     *
     * @mbg.generated
     */
    private BigDecimal reserve4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.RESERVE5
     *
     * @mbg.generated
     */
    private BigDecimal reserve5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.RESERVE6
     *
     * @mbg.generated
     */
    private BigDecimal reserve6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.CONTACT
     *
     * @mbg.generated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.COMPANY
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.CITY
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.PROVINCE
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.COUNTRY
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.POSTCODE
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.DISTRICT
     *
     * @mbg.generated
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.TEL
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.FAX
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.USERID
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.RESERVE8
     *
     * @mbg.generated
     */
    private BigDecimal reserve8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.RESERVE7
     *
     * @mbg.generated
     */
    private BigDecimal reserve7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.STREET1
     *
     * @mbg.generated
     */
    private String street1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_ckyuser.STREET2
     *
     * @mbg.generated
     */
    private String street2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_ckyuser
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.SID
     *
     * @return the value of db_ckyuser.SID
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.SID
     *
     * @param sid the value for db_ckyuser.SID
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.EXPRESSID
     *
     * @return the value of db_ckyuser.EXPRESSID
     *
     * @mbg.generated
     */
    public String getExpressid() {
        return expressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.EXPRESSID
     *
     * @param expressid the value for db_ckyuser.EXPRESSID
     *
     * @mbg.generated
     */
    public void setExpressid(String expressid) {
        this.expressid = expressid == null ? null : expressid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.TOKENID
     *
     * @return the value of db_ckyuser.TOKENID
     *
     * @mbg.generated
     */
    public String getTokenid() {
        return tokenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.TOKENID
     *
     * @param tokenid the value for db_ckyuser.TOKENID
     *
     * @mbg.generated
     */
    public void setTokenid(String tokenid) {
        this.tokenid = tokenid == null ? null : tokenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.USERKEY
     *
     * @return the value of db_ckyuser.USERKEY
     *
     * @mbg.generated
     */
    public String getUserkey() {
        return userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.USERKEY
     *
     * @param userkey the value for db_ckyuser.USERKEY
     *
     * @mbg.generated
     */
    public void setUserkey(String userkey) {
        this.userkey = userkey == null ? null : userkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.CUSTOMUSERKEY
     *
     * @return the value of db_ckyuser.CUSTOMUSERKEY
     *
     * @mbg.generated
     */
    public String getCustomuserkey() {
        return customuserkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.CUSTOMUSERKEY
     *
     * @param customuserkey the value for db_ckyuser.CUSTOMUSERKEY
     *
     * @mbg.generated
     */
    public void setCustomuserkey(String customuserkey) {
        this.customuserkey = customuserkey == null ? null : customuserkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.OPER
     *
     * @return the value of db_ckyuser.OPER
     *
     * @mbg.generated
     */
    public String getOper() {
        return oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.OPER
     *
     * @param oper the value for db_ckyuser.OPER
     *
     * @mbg.generated
     */
    public void setOper(String oper) {
        this.oper = oper == null ? null : oper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.OPERTIME
     *
     * @return the value of db_ckyuser.OPERTIME
     *
     * @mbg.generated
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.OPERTIME
     *
     * @param opertime the value for db_ckyuser.OPERTIME
     *
     * @mbg.generated
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.FLAG
     *
     * @return the value of db_ckyuser.FLAG
     *
     * @mbg.generated
     */
    public BigDecimal getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.FLAG
     *
     * @param flag the value for db_ckyuser.FLAG
     *
     * @mbg.generated
     */
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.OPENFLAG
     *
     * @return the value of db_ckyuser.OPENFLAG
     *
     * @mbg.generated
     */
    public BigDecimal getOpenflag() {
        return openflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.OPENFLAG
     *
     * @param openflag the value for db_ckyuser.OPENFLAG
     *
     * @mbg.generated
     */
    public void setOpenflag(BigDecimal openflag) {
        this.openflag = openflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.CORPID
     *
     * @return the value of db_ckyuser.CORPID
     *
     * @mbg.generated
     */
    public String getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.CORPID
     *
     * @param corpid the value for db_ckyuser.CORPID
     *
     * @mbg.generated
     */
    public void setCorpid(String corpid) {
        this.corpid = corpid == null ? null : corpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.TYPEID
     *
     * @return the value of db_ckyuser.TYPEID
     *
     * @mbg.generated
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.TYPEID
     *
     * @param typeid the value for db_ckyuser.TYPEID
     *
     * @mbg.generated
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.TYPENAME
     *
     * @return the value of db_ckyuser.TYPENAME
     *
     * @mbg.generated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.TYPENAME
     *
     * @param typename the value for db_ckyuser.TYPENAME
     *
     * @mbg.generated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.TYPECOUNTRY
     *
     * @return the value of db_ckyuser.TYPECOUNTRY
     *
     * @mbg.generated
     */
    public String getTypecountry() {
        return typecountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.TYPECOUNTRY
     *
     * @param typecountry the value for db_ckyuser.TYPECOUNTRY
     *
     * @mbg.generated
     */
    public void setTypecountry(String typecountry) {
        this.typecountry = typecountry == null ? null : typecountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.RESERVE1
     *
     * @return the value of db_ckyuser.RESERVE1
     *
     * @mbg.generated
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.RESERVE1
     *
     * @param reserve1 the value for db_ckyuser.RESERVE1
     *
     * @mbg.generated
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.RESERVE2
     *
     * @return the value of db_ckyuser.RESERVE2
     *
     * @mbg.generated
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.RESERVE2
     *
     * @param reserve2 the value for db_ckyuser.RESERVE2
     *
     * @mbg.generated
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.RESERVE3
     *
     * @return the value of db_ckyuser.RESERVE3
     *
     * @mbg.generated
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.RESERVE3
     *
     * @param reserve3 the value for db_ckyuser.RESERVE3
     *
     * @mbg.generated
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.RESERVE4
     *
     * @return the value of db_ckyuser.RESERVE4
     *
     * @mbg.generated
     */
    public BigDecimal getReserve4() {
        return reserve4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.RESERVE4
     *
     * @param reserve4 the value for db_ckyuser.RESERVE4
     *
     * @mbg.generated
     */
    public void setReserve4(BigDecimal reserve4) {
        this.reserve4 = reserve4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.RESERVE5
     *
     * @return the value of db_ckyuser.RESERVE5
     *
     * @mbg.generated
     */
    public BigDecimal getReserve5() {
        return reserve5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.RESERVE5
     *
     * @param reserve5 the value for db_ckyuser.RESERVE5
     *
     * @mbg.generated
     */
    public void setReserve5(BigDecimal reserve5) {
        this.reserve5 = reserve5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.RESERVE6
     *
     * @return the value of db_ckyuser.RESERVE6
     *
     * @mbg.generated
     */
    public BigDecimal getReserve6() {
        return reserve6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.RESERVE6
     *
     * @param reserve6 the value for db_ckyuser.RESERVE6
     *
     * @mbg.generated
     */
    public void setReserve6(BigDecimal reserve6) {
        this.reserve6 = reserve6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.CONTACT
     *
     * @return the value of db_ckyuser.CONTACT
     *
     * @mbg.generated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.CONTACT
     *
     * @param contact the value for db_ckyuser.CONTACT
     *
     * @mbg.generated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.COMPANY
     *
     * @return the value of db_ckyuser.COMPANY
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.COMPANY
     *
     * @param company the value for db_ckyuser.COMPANY
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.CITY
     *
     * @return the value of db_ckyuser.CITY
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.CITY
     *
     * @param city the value for db_ckyuser.CITY
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.PROVINCE
     *
     * @return the value of db_ckyuser.PROVINCE
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.PROVINCE
     *
     * @param province the value for db_ckyuser.PROVINCE
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.COUNTRY
     *
     * @return the value of db_ckyuser.COUNTRY
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.COUNTRY
     *
     * @param country the value for db_ckyuser.COUNTRY
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.POSTCODE
     *
     * @return the value of db_ckyuser.POSTCODE
     *
     * @mbg.generated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.POSTCODE
     *
     * @param postcode the value for db_ckyuser.POSTCODE
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.DISTRICT
     *
     * @return the value of db_ckyuser.DISTRICT
     *
     * @mbg.generated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.DISTRICT
     *
     * @param district the value for db_ckyuser.DISTRICT
     *
     * @mbg.generated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.TEL
     *
     * @return the value of db_ckyuser.TEL
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.TEL
     *
     * @param tel the value for db_ckyuser.TEL
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.FAX
     *
     * @return the value of db_ckyuser.FAX
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.FAX
     *
     * @param fax the value for db_ckyuser.FAX
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.EMAIL
     *
     * @return the value of db_ckyuser.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.EMAIL
     *
     * @param email the value for db_ckyuser.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.USERID
     *
     * @return the value of db_ckyuser.USERID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.USERID
     *
     * @param userid the value for db_ckyuser.USERID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.RESERVE8
     *
     * @return the value of db_ckyuser.RESERVE8
     *
     * @mbg.generated
     */
    public BigDecimal getReserve8() {
        return reserve8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.RESERVE8
     *
     * @param reserve8 the value for db_ckyuser.RESERVE8
     *
     * @mbg.generated
     */
    public void setReserve8(BigDecimal reserve8) {
        this.reserve8 = reserve8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.RESERVE7
     *
     * @return the value of db_ckyuser.RESERVE7
     *
     * @mbg.generated
     */
    public BigDecimal getReserve7() {
        return reserve7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.RESERVE7
     *
     * @param reserve7 the value for db_ckyuser.RESERVE7
     *
     * @mbg.generated
     */
    public void setReserve7(BigDecimal reserve7) {
        this.reserve7 = reserve7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.STREET1
     *
     * @return the value of db_ckyuser.STREET1
     *
     * @mbg.generated
     */
    public String getStreet1() {
        return street1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.STREET1
     *
     * @param street1 the value for db_ckyuser.STREET1
     *
     * @mbg.generated
     */
    public void setStreet1(String street1) {
        this.street1 = street1 == null ? null : street1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_ckyuser.STREET2
     *
     * @return the value of db_ckyuser.STREET2
     *
     * @mbg.generated
     */
    public String getStreet2() {
        return street2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_ckyuser.STREET2
     *
     * @param street2 the value for db_ckyuser.STREET2
     *
     * @mbg.generated
     */
    public void setStreet2(String street2) {
        this.street2 = street2 == null ? null : street2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ckyuser
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbCkyuser other = (DbCkyuser) that;
        return (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
            && (this.getExpressid() == null ? other.getExpressid() == null : this.getExpressid().equals(other.getExpressid()))
            && (this.getTokenid() == null ? other.getTokenid() == null : this.getTokenid().equals(other.getTokenid()))
            && (this.getUserkey() == null ? other.getUserkey() == null : this.getUserkey().equals(other.getUserkey()))
            && (this.getCustomuserkey() == null ? other.getCustomuserkey() == null : this.getCustomuserkey().equals(other.getCustomuserkey()))
            && (this.getOper() == null ? other.getOper() == null : this.getOper().equals(other.getOper()))
            && (this.getOpertime() == null ? other.getOpertime() == null : this.getOpertime().equals(other.getOpertime()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getOpenflag() == null ? other.getOpenflag() == null : this.getOpenflag().equals(other.getOpenflag()))
            && (this.getCorpid() == null ? other.getCorpid() == null : this.getCorpid().equals(other.getCorpid()))
            && (this.getTypeid() == null ? other.getTypeid() == null : this.getTypeid().equals(other.getTypeid()))
            && (this.getTypename() == null ? other.getTypename() == null : this.getTypename().equals(other.getTypename()))
            && (this.getTypecountry() == null ? other.getTypecountry() == null : this.getTypecountry().equals(other.getTypecountry()))
            && (this.getReserve1() == null ? other.getReserve1() == null : this.getReserve1().equals(other.getReserve1()))
            && (this.getReserve2() == null ? other.getReserve2() == null : this.getReserve2().equals(other.getReserve2()))
            && (this.getReserve3() == null ? other.getReserve3() == null : this.getReserve3().equals(other.getReserve3()))
            && (this.getReserve4() == null ? other.getReserve4() == null : this.getReserve4().equals(other.getReserve4()))
            && (this.getReserve5() == null ? other.getReserve5() == null : this.getReserve5().equals(other.getReserve5()))
            && (this.getReserve6() == null ? other.getReserve6() == null : this.getReserve6().equals(other.getReserve6()))
            && (this.getContact() == null ? other.getContact() == null : this.getContact().equals(other.getContact()))
            && (this.getCompany() == null ? other.getCompany() == null : this.getCompany().equals(other.getCompany()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getPostcode() == null ? other.getPostcode() == null : this.getPostcode().equals(other.getPostcode()))
            && (this.getDistrict() == null ? other.getDistrict() == null : this.getDistrict().equals(other.getDistrict()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getReserve8() == null ? other.getReserve8() == null : this.getReserve8().equals(other.getReserve8()))
            && (this.getReserve7() == null ? other.getReserve7() == null : this.getReserve7().equals(other.getReserve7()))
            && (this.getStreet1() == null ? other.getStreet1() == null : this.getStreet1().equals(other.getStreet1()))
            && (this.getStreet2() == null ? other.getStreet2() == null : this.getStreet2().equals(other.getStreet2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ckyuser
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getExpressid() == null) ? 0 : getExpressid().hashCode());
        result = prime * result + ((getTokenid() == null) ? 0 : getTokenid().hashCode());
        result = prime * result + ((getUserkey() == null) ? 0 : getUserkey().hashCode());
        result = prime * result + ((getCustomuserkey() == null) ? 0 : getCustomuserkey().hashCode());
        result = prime * result + ((getOper() == null) ? 0 : getOper().hashCode());
        result = prime * result + ((getOpertime() == null) ? 0 : getOpertime().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getOpenflag() == null) ? 0 : getOpenflag().hashCode());
        result = prime * result + ((getCorpid() == null) ? 0 : getCorpid().hashCode());
        result = prime * result + ((getTypeid() == null) ? 0 : getTypeid().hashCode());
        result = prime * result + ((getTypename() == null) ? 0 : getTypename().hashCode());
        result = prime * result + ((getTypecountry() == null) ? 0 : getTypecountry().hashCode());
        result = prime * result + ((getReserve1() == null) ? 0 : getReserve1().hashCode());
        result = prime * result + ((getReserve2() == null) ? 0 : getReserve2().hashCode());
        result = prime * result + ((getReserve3() == null) ? 0 : getReserve3().hashCode());
        result = prime * result + ((getReserve4() == null) ? 0 : getReserve4().hashCode());
        result = prime * result + ((getReserve5() == null) ? 0 : getReserve5().hashCode());
        result = prime * result + ((getReserve6() == null) ? 0 : getReserve6().hashCode());
        result = prime * result + ((getContact() == null) ? 0 : getContact().hashCode());
        result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getPostcode() == null) ? 0 : getPostcode().hashCode());
        result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getReserve8() == null) ? 0 : getReserve8().hashCode());
        result = prime * result + ((getReserve7() == null) ? 0 : getReserve7().hashCode());
        result = prime * result + ((getStreet1() == null) ? 0 : getStreet1().hashCode());
        result = prime * result + ((getStreet2() == null) ? 0 : getStreet2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ckyuser
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", expressid=").append(expressid);
        sb.append(", tokenid=").append(tokenid);
        sb.append(", userkey=").append(userkey);
        sb.append(", customuserkey=").append(customuserkey);
        sb.append(", oper=").append(oper);
        sb.append(", opertime=").append(opertime);
        sb.append(", flag=").append(flag);
        sb.append(", openflag=").append(openflag);
        sb.append(", corpid=").append(corpid);
        sb.append(", typeid=").append(typeid);
        sb.append(", typename=").append(typename);
        sb.append(", typecountry=").append(typecountry);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", reserve3=").append(reserve3);
        sb.append(", reserve4=").append(reserve4);
        sb.append(", reserve5=").append(reserve5);
        sb.append(", reserve6=").append(reserve6);
        sb.append(", contact=").append(contact);
        sb.append(", company=").append(company);
        sb.append(", city=").append(city);
        sb.append(", province=").append(province);
        sb.append(", country=").append(country);
        sb.append(", postcode=").append(postcode);
        sb.append(", district=").append(district);
        sb.append(", tel=").append(tel);
        sb.append(", fax=").append(fax);
        sb.append(", email=").append(email);
        sb.append(", userid=").append(userid);
        sb.append(", reserve8=").append(reserve8);
        sb.append(", reserve7=").append(reserve7);
        sb.append(", street1=").append(street1);
        sb.append(", street2=").append(street2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}