package com.bean.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class DbCneexpresstype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_cneexpresstype.SEQUENCEID
     *
     * @mbg.generated
     */
    private BigDecimal sequenceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_cneexpresstype.EXPRESSTYPE
     *
     * @mbg.generated
     */
    private String expresstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_cneexpresstype
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_cneexpresstype.SEQUENCEID
     *
     * @return the value of db_cneexpresstype.SEQUENCEID
     *
     * @mbg.generated
     */
    public BigDecimal getSequenceid() {
        return sequenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_cneexpresstype.SEQUENCEID
     *
     * @param sequenceid the value for db_cneexpresstype.SEQUENCEID
     *
     * @mbg.generated
     */
    public void setSequenceid(BigDecimal sequenceid) {
        this.sequenceid = sequenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_cneexpresstype.EXPRESSTYPE
     *
     * @return the value of db_cneexpresstype.EXPRESSTYPE
     *
     * @mbg.generated
     */
    public String getExpresstype() {
        return expresstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_cneexpresstype.EXPRESSTYPE
     *
     * @param expresstype the value for db_cneexpresstype.EXPRESSTYPE
     *
     * @mbg.generated
     */
    public void setExpresstype(String expresstype) {
        this.expresstype = expresstype == null ? null : expresstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_cneexpresstype
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbCneexpresstype other = (DbCneexpresstype) that;
        return (this.getSequenceid() == null ? other.getSequenceid() == null : this.getSequenceid().equals(other.getSequenceid()))
            && (this.getExpresstype() == null ? other.getExpresstype() == null : this.getExpresstype().equals(other.getExpresstype()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_cneexpresstype
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSequenceid() == null) ? 0 : getSequenceid().hashCode());
        result = prime * result + ((getExpresstype() == null) ? 0 : getExpresstype().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_cneexpresstype
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sequenceid=").append(sequenceid);
        sb.append(", expresstype=").append(expresstype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}