package com.bean.model;

import java.io.Serializable;
import java.util.Date;

public class DbDowneubseller implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.SID
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.TOKENTYPE
     *
     * @mbg.generated
     */
    private String tokentype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.TOKENID
     *
     * @mbg.generated
     */
    private String tokenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.COMPANY
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.COMPANYEN
     *
     * @mbg.generated
     */
    private String companyen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.CONTACT
     *
     * @mbg.generated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.CONTACTEN
     *
     * @mbg.generated
     */
    private String contacten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.STREET
     *
     * @mbg.generated
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.STREETEN
     *
     * @mbg.generated
     */
    private String streeten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.PROVINCE
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.PROVINCEEN
     *
     * @mbg.generated
     */
    private String provinceen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.PROVINCEID
     *
     * @mbg.generated
     */
    private String provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.CITY
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.CITYEN
     *
     * @mbg.generated
     */
    private String cityen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.CITYID
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.DISTRICT
     *
     * @mbg.generated
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.DISTRICTEN
     *
     * @mbg.generated
     */
    private String districten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.DISTRICTID
     *
     * @mbg.generated
     */
    private String districtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.COUNTRYID
     *
     * @mbg.generated
     */
    private String countryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.COUNTRY
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.COUNTRYEN
     *
     * @mbg.generated
     */
    private String countryen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.POSTCODE
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.POSTCODE2
     *
     * @mbg.generated
     */
    private String postcode2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.OPENFLAG
     *
     * @mbg.generated
     */
    private String openflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.OPER
     *
     * @mbg.generated
     */
    private String oper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.OPERTIME
     *
     * @mbg.generated
     */
    private Date opertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.RESERVE1
     *
     * @mbg.generated
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.RESERVE2
     *
     * @mbg.generated
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.RESERVE3
     *
     * @mbg.generated
     */
    private String reserve3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_downeubseller.RESERVE4
     *
     * @mbg.generated
     */
    private String reserve4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_downeubseller
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.SID
     *
     * @return the value of db_downeubseller.SID
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.SID
     *
     * @param sid the value for db_downeubseller.SID
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.NAME
     *
     * @return the value of db_downeubseller.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.NAME
     *
     * @param name the value for db_downeubseller.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.TOKENTYPE
     *
     * @return the value of db_downeubseller.TOKENTYPE
     *
     * @mbg.generated
     */
    public String getTokentype() {
        return tokentype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.TOKENTYPE
     *
     * @param tokentype the value for db_downeubseller.TOKENTYPE
     *
     * @mbg.generated
     */
    public void setTokentype(String tokentype) {
        this.tokentype = tokentype == null ? null : tokentype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.TOKENID
     *
     * @return the value of db_downeubseller.TOKENID
     *
     * @mbg.generated
     */
    public String getTokenid() {
        return tokenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.TOKENID
     *
     * @param tokenid the value for db_downeubseller.TOKENID
     *
     * @mbg.generated
     */
    public void setTokenid(String tokenid) {
        this.tokenid = tokenid == null ? null : tokenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.COMPANY
     *
     * @return the value of db_downeubseller.COMPANY
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.COMPANY
     *
     * @param company the value for db_downeubseller.COMPANY
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.COMPANYEN
     *
     * @return the value of db_downeubseller.COMPANYEN
     *
     * @mbg.generated
     */
    public String getCompanyen() {
        return companyen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.COMPANYEN
     *
     * @param companyen the value for db_downeubseller.COMPANYEN
     *
     * @mbg.generated
     */
    public void setCompanyen(String companyen) {
        this.companyen = companyen == null ? null : companyen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.CONTACT
     *
     * @return the value of db_downeubseller.CONTACT
     *
     * @mbg.generated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.CONTACT
     *
     * @param contact the value for db_downeubseller.CONTACT
     *
     * @mbg.generated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.CONTACTEN
     *
     * @return the value of db_downeubseller.CONTACTEN
     *
     * @mbg.generated
     */
    public String getContacten() {
        return contacten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.CONTACTEN
     *
     * @param contacten the value for db_downeubseller.CONTACTEN
     *
     * @mbg.generated
     */
    public void setContacten(String contacten) {
        this.contacten = contacten == null ? null : contacten.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.STREET
     *
     * @return the value of db_downeubseller.STREET
     *
     * @mbg.generated
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.STREET
     *
     * @param street the value for db_downeubseller.STREET
     *
     * @mbg.generated
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.STREETEN
     *
     * @return the value of db_downeubseller.STREETEN
     *
     * @mbg.generated
     */
    public String getStreeten() {
        return streeten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.STREETEN
     *
     * @param streeten the value for db_downeubseller.STREETEN
     *
     * @mbg.generated
     */
    public void setStreeten(String streeten) {
        this.streeten = streeten == null ? null : streeten.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.PROVINCE
     *
     * @return the value of db_downeubseller.PROVINCE
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.PROVINCE
     *
     * @param province the value for db_downeubseller.PROVINCE
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.PROVINCEEN
     *
     * @return the value of db_downeubseller.PROVINCEEN
     *
     * @mbg.generated
     */
    public String getProvinceen() {
        return provinceen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.PROVINCEEN
     *
     * @param provinceen the value for db_downeubseller.PROVINCEEN
     *
     * @mbg.generated
     */
    public void setProvinceen(String provinceen) {
        this.provinceen = provinceen == null ? null : provinceen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.PROVINCEID
     *
     * @return the value of db_downeubseller.PROVINCEID
     *
     * @mbg.generated
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.PROVINCEID
     *
     * @param provinceid the value for db_downeubseller.PROVINCEID
     *
     * @mbg.generated
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.CITY
     *
     * @return the value of db_downeubseller.CITY
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.CITY
     *
     * @param city the value for db_downeubseller.CITY
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.CITYEN
     *
     * @return the value of db_downeubseller.CITYEN
     *
     * @mbg.generated
     */
    public String getCityen() {
        return cityen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.CITYEN
     *
     * @param cityen the value for db_downeubseller.CITYEN
     *
     * @mbg.generated
     */
    public void setCityen(String cityen) {
        this.cityen = cityen == null ? null : cityen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.CITYID
     *
     * @return the value of db_downeubseller.CITYID
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.CITYID
     *
     * @param cityid the value for db_downeubseller.CITYID
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.DISTRICT
     *
     * @return the value of db_downeubseller.DISTRICT
     *
     * @mbg.generated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.DISTRICT
     *
     * @param district the value for db_downeubseller.DISTRICT
     *
     * @mbg.generated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.DISTRICTEN
     *
     * @return the value of db_downeubseller.DISTRICTEN
     *
     * @mbg.generated
     */
    public String getDistricten() {
        return districten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.DISTRICTEN
     *
     * @param districten the value for db_downeubseller.DISTRICTEN
     *
     * @mbg.generated
     */
    public void setDistricten(String districten) {
        this.districten = districten == null ? null : districten.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.DISTRICTID
     *
     * @return the value of db_downeubseller.DISTRICTID
     *
     * @mbg.generated
     */
    public String getDistrictid() {
        return districtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.DISTRICTID
     *
     * @param districtid the value for db_downeubseller.DISTRICTID
     *
     * @mbg.generated
     */
    public void setDistrictid(String districtid) {
        this.districtid = districtid == null ? null : districtid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.COUNTRYID
     *
     * @return the value of db_downeubseller.COUNTRYID
     *
     * @mbg.generated
     */
    public String getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.COUNTRYID
     *
     * @param countryid the value for db_downeubseller.COUNTRYID
     *
     * @mbg.generated
     */
    public void setCountryid(String countryid) {
        this.countryid = countryid == null ? null : countryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.COUNTRY
     *
     * @return the value of db_downeubseller.COUNTRY
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.COUNTRY
     *
     * @param country the value for db_downeubseller.COUNTRY
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.COUNTRYEN
     *
     * @return the value of db_downeubseller.COUNTRYEN
     *
     * @mbg.generated
     */
    public String getCountryen() {
        return countryen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.COUNTRYEN
     *
     * @param countryen the value for db_downeubseller.COUNTRYEN
     *
     * @mbg.generated
     */
    public void setCountryen(String countryen) {
        this.countryen = countryen == null ? null : countryen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.POSTCODE
     *
     * @return the value of db_downeubseller.POSTCODE
     *
     * @mbg.generated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.POSTCODE
     *
     * @param postcode the value for db_downeubseller.POSTCODE
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.POSTCODE2
     *
     * @return the value of db_downeubseller.POSTCODE2
     *
     * @mbg.generated
     */
    public String getPostcode2() {
        return postcode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.POSTCODE2
     *
     * @param postcode2 the value for db_downeubseller.POSTCODE2
     *
     * @mbg.generated
     */
    public void setPostcode2(String postcode2) {
        this.postcode2 = postcode2 == null ? null : postcode2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.MOBILE
     *
     * @return the value of db_downeubseller.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.MOBILE
     *
     * @param mobile the value for db_downeubseller.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.PHONE
     *
     * @return the value of db_downeubseller.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.PHONE
     *
     * @param phone the value for db_downeubseller.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.EMAIL
     *
     * @return the value of db_downeubseller.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.EMAIL
     *
     * @param email the value for db_downeubseller.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.OPENFLAG
     *
     * @return the value of db_downeubseller.OPENFLAG
     *
     * @mbg.generated
     */
    public String getOpenflag() {
        return openflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.OPENFLAG
     *
     * @param openflag the value for db_downeubseller.OPENFLAG
     *
     * @mbg.generated
     */
    public void setOpenflag(String openflag) {
        this.openflag = openflag == null ? null : openflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.OPER
     *
     * @return the value of db_downeubseller.OPER
     *
     * @mbg.generated
     */
    public String getOper() {
        return oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.OPER
     *
     * @param oper the value for db_downeubseller.OPER
     *
     * @mbg.generated
     */
    public void setOper(String oper) {
        this.oper = oper == null ? null : oper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.OPERTIME
     *
     * @return the value of db_downeubseller.OPERTIME
     *
     * @mbg.generated
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.OPERTIME
     *
     * @param opertime the value for db_downeubseller.OPERTIME
     *
     * @mbg.generated
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.RESERVE1
     *
     * @return the value of db_downeubseller.RESERVE1
     *
     * @mbg.generated
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.RESERVE1
     *
     * @param reserve1 the value for db_downeubseller.RESERVE1
     *
     * @mbg.generated
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.RESERVE2
     *
     * @return the value of db_downeubseller.RESERVE2
     *
     * @mbg.generated
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.RESERVE2
     *
     * @param reserve2 the value for db_downeubseller.RESERVE2
     *
     * @mbg.generated
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.RESERVE3
     *
     * @return the value of db_downeubseller.RESERVE3
     *
     * @mbg.generated
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.RESERVE3
     *
     * @param reserve3 the value for db_downeubseller.RESERVE3
     *
     * @mbg.generated
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_downeubseller.RESERVE4
     *
     * @return the value of db_downeubseller.RESERVE4
     *
     * @mbg.generated
     */
    public String getReserve4() {
        return reserve4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_downeubseller.RESERVE4
     *
     * @param reserve4 the value for db_downeubseller.RESERVE4
     *
     * @mbg.generated
     */
    public void setReserve4(String reserve4) {
        this.reserve4 = reserve4 == null ? null : reserve4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_downeubseller
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbDowneubseller other = (DbDowneubseller) that;
        return (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTokentype() == null ? other.getTokentype() == null : this.getTokentype().equals(other.getTokentype()))
            && (this.getTokenid() == null ? other.getTokenid() == null : this.getTokenid().equals(other.getTokenid()))
            && (this.getCompany() == null ? other.getCompany() == null : this.getCompany().equals(other.getCompany()))
            && (this.getCompanyen() == null ? other.getCompanyen() == null : this.getCompanyen().equals(other.getCompanyen()))
            && (this.getContact() == null ? other.getContact() == null : this.getContact().equals(other.getContact()))
            && (this.getContacten() == null ? other.getContacten() == null : this.getContacten().equals(other.getContacten()))
            && (this.getStreet() == null ? other.getStreet() == null : this.getStreet().equals(other.getStreet()))
            && (this.getStreeten() == null ? other.getStreeten() == null : this.getStreeten().equals(other.getStreeten()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getProvinceen() == null ? other.getProvinceen() == null : this.getProvinceen().equals(other.getProvinceen()))
            && (this.getProvinceid() == null ? other.getProvinceid() == null : this.getProvinceid().equals(other.getProvinceid()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getCityen() == null ? other.getCityen() == null : this.getCityen().equals(other.getCityen()))
            && (this.getCityid() == null ? other.getCityid() == null : this.getCityid().equals(other.getCityid()))
            && (this.getDistrict() == null ? other.getDistrict() == null : this.getDistrict().equals(other.getDistrict()))
            && (this.getDistricten() == null ? other.getDistricten() == null : this.getDistricten().equals(other.getDistricten()))
            && (this.getDistrictid() == null ? other.getDistrictid() == null : this.getDistrictid().equals(other.getDistrictid()))
            && (this.getCountryid() == null ? other.getCountryid() == null : this.getCountryid().equals(other.getCountryid()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getCountryen() == null ? other.getCountryen() == null : this.getCountryen().equals(other.getCountryen()))
            && (this.getPostcode() == null ? other.getPostcode() == null : this.getPostcode().equals(other.getPostcode()))
            && (this.getPostcode2() == null ? other.getPostcode2() == null : this.getPostcode2().equals(other.getPostcode2()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getOpenflag() == null ? other.getOpenflag() == null : this.getOpenflag().equals(other.getOpenflag()))
            && (this.getOper() == null ? other.getOper() == null : this.getOper().equals(other.getOper()))
            && (this.getOpertime() == null ? other.getOpertime() == null : this.getOpertime().equals(other.getOpertime()))
            && (this.getReserve1() == null ? other.getReserve1() == null : this.getReserve1().equals(other.getReserve1()))
            && (this.getReserve2() == null ? other.getReserve2() == null : this.getReserve2().equals(other.getReserve2()))
            && (this.getReserve3() == null ? other.getReserve3() == null : this.getReserve3().equals(other.getReserve3()))
            && (this.getReserve4() == null ? other.getReserve4() == null : this.getReserve4().equals(other.getReserve4()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_downeubseller
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTokentype() == null) ? 0 : getTokentype().hashCode());
        result = prime * result + ((getTokenid() == null) ? 0 : getTokenid().hashCode());
        result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
        result = prime * result + ((getCompanyen() == null) ? 0 : getCompanyen().hashCode());
        result = prime * result + ((getContact() == null) ? 0 : getContact().hashCode());
        result = prime * result + ((getContacten() == null) ? 0 : getContacten().hashCode());
        result = prime * result + ((getStreet() == null) ? 0 : getStreet().hashCode());
        result = prime * result + ((getStreeten() == null) ? 0 : getStreeten().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getProvinceen() == null) ? 0 : getProvinceen().hashCode());
        result = prime * result + ((getProvinceid() == null) ? 0 : getProvinceid().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getCityen() == null) ? 0 : getCityen().hashCode());
        result = prime * result + ((getCityid() == null) ? 0 : getCityid().hashCode());
        result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getDistricten() == null) ? 0 : getDistricten().hashCode());
        result = prime * result + ((getDistrictid() == null) ? 0 : getDistrictid().hashCode());
        result = prime * result + ((getCountryid() == null) ? 0 : getCountryid().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getCountryen() == null) ? 0 : getCountryen().hashCode());
        result = prime * result + ((getPostcode() == null) ? 0 : getPostcode().hashCode());
        result = prime * result + ((getPostcode2() == null) ? 0 : getPostcode2().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getOpenflag() == null) ? 0 : getOpenflag().hashCode());
        result = prime * result + ((getOper() == null) ? 0 : getOper().hashCode());
        result = prime * result + ((getOpertime() == null) ? 0 : getOpertime().hashCode());
        result = prime * result + ((getReserve1() == null) ? 0 : getReserve1().hashCode());
        result = prime * result + ((getReserve2() == null) ? 0 : getReserve2().hashCode());
        result = prime * result + ((getReserve3() == null) ? 0 : getReserve3().hashCode());
        result = prime * result + ((getReserve4() == null) ? 0 : getReserve4().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_downeubseller
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", name=").append(name);
        sb.append(", tokentype=").append(tokentype);
        sb.append(", tokenid=").append(tokenid);
        sb.append(", company=").append(company);
        sb.append(", companyen=").append(companyen);
        sb.append(", contact=").append(contact);
        sb.append(", contacten=").append(contacten);
        sb.append(", street=").append(street);
        sb.append(", streeten=").append(streeten);
        sb.append(", province=").append(province);
        sb.append(", provinceen=").append(provinceen);
        sb.append(", provinceid=").append(provinceid);
        sb.append(", city=").append(city);
        sb.append(", cityen=").append(cityen);
        sb.append(", cityid=").append(cityid);
        sb.append(", district=").append(district);
        sb.append(", districten=").append(districten);
        sb.append(", districtid=").append(districtid);
        sb.append(", countryid=").append(countryid);
        sb.append(", country=").append(country);
        sb.append(", countryen=").append(countryen);
        sb.append(", postcode=").append(postcode);
        sb.append(", postcode2=").append(postcode2);
        sb.append(", mobile=").append(mobile);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", openflag=").append(openflag);
        sb.append(", oper=").append(oper);
        sb.append(", opertime=").append(opertime);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", reserve3=").append(reserve3);
        sb.append(", reserve4=").append(reserve4);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}