package com.bean.model;

import java.io.Serializable;
import java.util.Date;

public class DbManystoragebinlog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.SEQUENCEID
     *
     * @mbg.generated
     */
    private String sequenceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.PRODUCTID
     *
     * @mbg.generated
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.OPERTIME
     *
     * @mbg.generated
     */
    private Date opertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.OPER
     *
     * @mbg.generated
     */
    private String oper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.OPENFLAG
     *
     * @mbg.generated
     */
    private String openflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.CORPID
     *
     * @mbg.generated
     */
    private String corpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.OPERTYPE
     *
     * @mbg.generated
     */
    private String opertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.RESERVE1
     *
     * @mbg.generated
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.RESERVE2
     *
     * @mbg.generated
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.RESERVE3
     *
     * @mbg.generated
     */
    private String reserve3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.STORAGEBINFLAG
     *
     * @mbg.generated
     */
    private String storagebinflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.MAINSKU
     *
     * @mbg.generated
     */
    private String mainsku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.STORAGEID
     *
     * @mbg.generated
     */
    private String storageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.PRODUCTNAME
     *
     * @mbg.generated
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.STORAGENAME
     *
     * @mbg.generated
     */
    private String storagename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.DESCR
     *
     * @mbg.generated
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manystoragebinlog.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_manystoragebinlog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.SEQUENCEID
     *
     * @return the value of db_manystoragebinlog.SEQUENCEID
     *
     * @mbg.generated
     */
    public String getSequenceid() {
        return sequenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.SEQUENCEID
     *
     * @param sequenceid the value for db_manystoragebinlog.SEQUENCEID
     *
     * @mbg.generated
     */
    public void setSequenceid(String sequenceid) {
        this.sequenceid = sequenceid == null ? null : sequenceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.PRODUCTID
     *
     * @return the value of db_manystoragebinlog.PRODUCTID
     *
     * @mbg.generated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.PRODUCTID
     *
     * @param productid the value for db_manystoragebinlog.PRODUCTID
     *
     * @mbg.generated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.OPERTIME
     *
     * @return the value of db_manystoragebinlog.OPERTIME
     *
     * @mbg.generated
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.OPERTIME
     *
     * @param opertime the value for db_manystoragebinlog.OPERTIME
     *
     * @mbg.generated
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.OPER
     *
     * @return the value of db_manystoragebinlog.OPER
     *
     * @mbg.generated
     */
    public String getOper() {
        return oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.OPER
     *
     * @param oper the value for db_manystoragebinlog.OPER
     *
     * @mbg.generated
     */
    public void setOper(String oper) {
        this.oper = oper == null ? null : oper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.OPENFLAG
     *
     * @return the value of db_manystoragebinlog.OPENFLAG
     *
     * @mbg.generated
     */
    public String getOpenflag() {
        return openflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.OPENFLAG
     *
     * @param openflag the value for db_manystoragebinlog.OPENFLAG
     *
     * @mbg.generated
     */
    public void setOpenflag(String openflag) {
        this.openflag = openflag == null ? null : openflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.CORPID
     *
     * @return the value of db_manystoragebinlog.CORPID
     *
     * @mbg.generated
     */
    public String getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.CORPID
     *
     * @param corpid the value for db_manystoragebinlog.CORPID
     *
     * @mbg.generated
     */
    public void setCorpid(String corpid) {
        this.corpid = corpid == null ? null : corpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.NAME
     *
     * @return the value of db_manystoragebinlog.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.NAME
     *
     * @param name the value for db_manystoragebinlog.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.OPERTYPE
     *
     * @return the value of db_manystoragebinlog.OPERTYPE
     *
     * @mbg.generated
     */
    public String getOpertype() {
        return opertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.OPERTYPE
     *
     * @param opertype the value for db_manystoragebinlog.OPERTYPE
     *
     * @mbg.generated
     */
    public void setOpertype(String opertype) {
        this.opertype = opertype == null ? null : opertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.RESERVE1
     *
     * @return the value of db_manystoragebinlog.RESERVE1
     *
     * @mbg.generated
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.RESERVE1
     *
     * @param reserve1 the value for db_manystoragebinlog.RESERVE1
     *
     * @mbg.generated
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.RESERVE2
     *
     * @return the value of db_manystoragebinlog.RESERVE2
     *
     * @mbg.generated
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.RESERVE2
     *
     * @param reserve2 the value for db_manystoragebinlog.RESERVE2
     *
     * @mbg.generated
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.RESERVE3
     *
     * @return the value of db_manystoragebinlog.RESERVE3
     *
     * @mbg.generated
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.RESERVE3
     *
     * @param reserve3 the value for db_manystoragebinlog.RESERVE3
     *
     * @mbg.generated
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.STORAGEBINFLAG
     *
     * @return the value of db_manystoragebinlog.STORAGEBINFLAG
     *
     * @mbg.generated
     */
    public String getStoragebinflag() {
        return storagebinflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.STORAGEBINFLAG
     *
     * @param storagebinflag the value for db_manystoragebinlog.STORAGEBINFLAG
     *
     * @mbg.generated
     */
    public void setStoragebinflag(String storagebinflag) {
        this.storagebinflag = storagebinflag == null ? null : storagebinflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.MAINSKU
     *
     * @return the value of db_manystoragebinlog.MAINSKU
     *
     * @mbg.generated
     */
    public String getMainsku() {
        return mainsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.MAINSKU
     *
     * @param mainsku the value for db_manystoragebinlog.MAINSKU
     *
     * @mbg.generated
     */
    public void setMainsku(String mainsku) {
        this.mainsku = mainsku == null ? null : mainsku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.STORAGEID
     *
     * @return the value of db_manystoragebinlog.STORAGEID
     *
     * @mbg.generated
     */
    public String getStorageid() {
        return storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.STORAGEID
     *
     * @param storageid the value for db_manystoragebinlog.STORAGEID
     *
     * @mbg.generated
     */
    public void setStorageid(String storageid) {
        this.storageid = storageid == null ? null : storageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.PRODUCTNAME
     *
     * @return the value of db_manystoragebinlog.PRODUCTNAME
     *
     * @mbg.generated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.PRODUCTNAME
     *
     * @param productname the value for db_manystoragebinlog.PRODUCTNAME
     *
     * @mbg.generated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.STORAGENAME
     *
     * @return the value of db_manystoragebinlog.STORAGENAME
     *
     * @mbg.generated
     */
    public String getStoragename() {
        return storagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.STORAGENAME
     *
     * @param storagename the value for db_manystoragebinlog.STORAGENAME
     *
     * @mbg.generated
     */
    public void setStoragename(String storagename) {
        this.storagename = storagename == null ? null : storagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.DESCR
     *
     * @return the value of db_manystoragebinlog.DESCR
     *
     * @mbg.generated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.DESCR
     *
     * @param descr the value for db_manystoragebinlog.DESCR
     *
     * @mbg.generated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manystoragebinlog.CONTENT
     *
     * @return the value of db_manystoragebinlog.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manystoragebinlog.CONTENT
     *
     * @param content the value for db_manystoragebinlog.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_manystoragebinlog
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbManystoragebinlog other = (DbManystoragebinlog) that;
        return (this.getSequenceid() == null ? other.getSequenceid() == null : this.getSequenceid().equals(other.getSequenceid()))
            && (this.getProductid() == null ? other.getProductid() == null : this.getProductid().equals(other.getProductid()))
            && (this.getOpertime() == null ? other.getOpertime() == null : this.getOpertime().equals(other.getOpertime()))
            && (this.getOper() == null ? other.getOper() == null : this.getOper().equals(other.getOper()))
            && (this.getOpenflag() == null ? other.getOpenflag() == null : this.getOpenflag().equals(other.getOpenflag()))
            && (this.getCorpid() == null ? other.getCorpid() == null : this.getCorpid().equals(other.getCorpid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getOpertype() == null ? other.getOpertype() == null : this.getOpertype().equals(other.getOpertype()))
            && (this.getReserve1() == null ? other.getReserve1() == null : this.getReserve1().equals(other.getReserve1()))
            && (this.getReserve2() == null ? other.getReserve2() == null : this.getReserve2().equals(other.getReserve2()))
            && (this.getReserve3() == null ? other.getReserve3() == null : this.getReserve3().equals(other.getReserve3()))
            && (this.getStoragebinflag() == null ? other.getStoragebinflag() == null : this.getStoragebinflag().equals(other.getStoragebinflag()))
            && (this.getMainsku() == null ? other.getMainsku() == null : this.getMainsku().equals(other.getMainsku()))
            && (this.getStorageid() == null ? other.getStorageid() == null : this.getStorageid().equals(other.getStorageid()))
            && (this.getProductname() == null ? other.getProductname() == null : this.getProductname().equals(other.getProductname()))
            && (this.getStoragename() == null ? other.getStoragename() == null : this.getStoragename().equals(other.getStoragename()))
            && (this.getDescr() == null ? other.getDescr() == null : this.getDescr().equals(other.getDescr()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_manystoragebinlog
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSequenceid() == null) ? 0 : getSequenceid().hashCode());
        result = prime * result + ((getProductid() == null) ? 0 : getProductid().hashCode());
        result = prime * result + ((getOpertime() == null) ? 0 : getOpertime().hashCode());
        result = prime * result + ((getOper() == null) ? 0 : getOper().hashCode());
        result = prime * result + ((getOpenflag() == null) ? 0 : getOpenflag().hashCode());
        result = prime * result + ((getCorpid() == null) ? 0 : getCorpid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getOpertype() == null) ? 0 : getOpertype().hashCode());
        result = prime * result + ((getReserve1() == null) ? 0 : getReserve1().hashCode());
        result = prime * result + ((getReserve2() == null) ? 0 : getReserve2().hashCode());
        result = prime * result + ((getReserve3() == null) ? 0 : getReserve3().hashCode());
        result = prime * result + ((getStoragebinflag() == null) ? 0 : getStoragebinflag().hashCode());
        result = prime * result + ((getMainsku() == null) ? 0 : getMainsku().hashCode());
        result = prime * result + ((getStorageid() == null) ? 0 : getStorageid().hashCode());
        result = prime * result + ((getProductname() == null) ? 0 : getProductname().hashCode());
        result = prime * result + ((getStoragename() == null) ? 0 : getStoragename().hashCode());
        result = prime * result + ((getDescr() == null) ? 0 : getDescr().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_manystoragebinlog
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sequenceid=").append(sequenceid);
        sb.append(", productid=").append(productid);
        sb.append(", opertime=").append(opertime);
        sb.append(", oper=").append(oper);
        sb.append(", openflag=").append(openflag);
        sb.append(", corpid=").append(corpid);
        sb.append(", name=").append(name);
        sb.append(", opertype=").append(opertype);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", reserve3=").append(reserve3);
        sb.append(", storagebinflag=").append(storagebinflag);
        sb.append(", mainsku=").append(mainsku);
        sb.append(", storageid=").append(storageid);
        sb.append(", productname=").append(productname);
        sb.append(", storagename=").append(storagename);
        sb.append(", descr=").append(descr);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}