package com.bean.model;

import java.io.Serializable;

public class DbProductcontent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_productcontent.PRODUCTID
     *
     * @mbg.generated
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_productcontent.CLOBCONTENT
     *
     * @mbg.generated
     */
    private String clobcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_productcontent
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_productcontent.PRODUCTID
     *
     * @return the value of db_productcontent.PRODUCTID
     *
     * @mbg.generated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_productcontent.PRODUCTID
     *
     * @param productid the value for db_productcontent.PRODUCTID
     *
     * @mbg.generated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_productcontent.CLOBCONTENT
     *
     * @return the value of db_productcontent.CLOBCONTENT
     *
     * @mbg.generated
     */
    public String getClobcontent() {
        return clobcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_productcontent.CLOBCONTENT
     *
     * @param clobcontent the value for db_productcontent.CLOBCONTENT
     *
     * @mbg.generated
     */
    public void setClobcontent(String clobcontent) {
        this.clobcontent = clobcontent == null ? null : clobcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_productcontent
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbProductcontent other = (DbProductcontent) that;
        return (this.getProductid() == null ? other.getProductid() == null : this.getProductid().equals(other.getProductid()))
            && (this.getClobcontent() == null ? other.getClobcontent() == null : this.getClobcontent().equals(other.getClobcontent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_productcontent
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductid() == null) ? 0 : getProductid().hashCode());
        result = prime * result + ((getClobcontent() == null) ? 0 : getClobcontent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_productcontent
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productid=").append(productid);
        sb.append(", clobcontent=").append(clobcontent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}