package com.bean.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DbTasklog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.SEQUENCEID
     *
     * @mbg.generated
     */
    private String sequenceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.SID
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.STYPE
     *
     * @mbg.generated
     */
    private String stype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.STYPENAME
     *
     * @mbg.generated
     */
    private String stypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.OPER
     *
     * @mbg.generated
     */
    private String oper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.OPERTIME
     *
     * @mbg.generated
     */
    private Date opertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.TOOPER
     *
     * @mbg.generated
     */
    private String tooper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.TOOPERTIME
     *
     * @mbg.generated
     */
    private Date toopertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.STATUSNAME
     *
     * @mbg.generated
     */
    private String statusname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.SLEVEL
     *
     * @mbg.generated
     */
    private String slevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.CHECKRESULT
     *
     * @mbg.generated
     */
    private String checkresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.SCORES
     *
     * @mbg.generated
     */
    private BigDecimal scores;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.CHECKOPER
     *
     * @mbg.generated
     */
    private String checkoper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.CHECKTIME
     *
     * @mbg.generated
     */
    private Date checktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.PUBLICFLAG
     *
     * @mbg.generated
     */
    private String publicflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.RESERVE1
     *
     * @mbg.generated
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.RESERVE2
     *
     * @mbg.generated
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.RESERVE3
     *
     * @mbg.generated
     */
    private String reserve3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.RESERVE4
     *
     * @mbg.generated
     */
    private String reserve4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.RESERVE5
     *
     * @mbg.generated
     */
    private String reserve5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.ENDTIME
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.DATEDIFF
     *
     * @mbg.generated
     */
    private BigDecimal datediff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.CORPID
     *
     * @mbg.generated
     */
    private String corpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.OPERTYPE
     *
     * @mbg.generated
     */
    private String opertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.STATUSFLAG
     *
     * @mbg.generated
     */
    private String statusflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.CUSTOMERTYPE
     *
     * @mbg.generated
     */
    private String customertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.QUESTION
     *
     * @mbg.generated
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.ANSWER
     *
     * @mbg.generated
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.CHECKDESCR
     *
     * @mbg.generated
     */
    private String checkdescr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.MEMBER
     *
     * @mbg.generated
     */
    private String member;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_tasklog.CUSTOMERNAME
     *
     * @mbg.generated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_tasklog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.SEQUENCEID
     *
     * @return the value of db_tasklog.SEQUENCEID
     *
     * @mbg.generated
     */
    public String getSequenceid() {
        return sequenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.SEQUENCEID
     *
     * @param sequenceid the value for db_tasklog.SEQUENCEID
     *
     * @mbg.generated
     */
    public void setSequenceid(String sequenceid) {
        this.sequenceid = sequenceid == null ? null : sequenceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.SID
     *
     * @return the value of db_tasklog.SID
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.SID
     *
     * @param sid the value for db_tasklog.SID
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.STYPE
     *
     * @return the value of db_tasklog.STYPE
     *
     * @mbg.generated
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.STYPE
     *
     * @param stype the value for db_tasklog.STYPE
     *
     * @mbg.generated
     */
    public void setStype(String stype) {
        this.stype = stype == null ? null : stype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.STYPENAME
     *
     * @return the value of db_tasklog.STYPENAME
     *
     * @mbg.generated
     */
    public String getStypename() {
        return stypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.STYPENAME
     *
     * @param stypename the value for db_tasklog.STYPENAME
     *
     * @mbg.generated
     */
    public void setStypename(String stypename) {
        this.stypename = stypename == null ? null : stypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.OPER
     *
     * @return the value of db_tasklog.OPER
     *
     * @mbg.generated
     */
    public String getOper() {
        return oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.OPER
     *
     * @param oper the value for db_tasklog.OPER
     *
     * @mbg.generated
     */
    public void setOper(String oper) {
        this.oper = oper == null ? null : oper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.OPERTIME
     *
     * @return the value of db_tasklog.OPERTIME
     *
     * @mbg.generated
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.OPERTIME
     *
     * @param opertime the value for db_tasklog.OPERTIME
     *
     * @mbg.generated
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.TOOPER
     *
     * @return the value of db_tasklog.TOOPER
     *
     * @mbg.generated
     */
    public String getTooper() {
        return tooper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.TOOPER
     *
     * @param tooper the value for db_tasklog.TOOPER
     *
     * @mbg.generated
     */
    public void setTooper(String tooper) {
        this.tooper = tooper == null ? null : tooper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.TOOPERTIME
     *
     * @return the value of db_tasklog.TOOPERTIME
     *
     * @mbg.generated
     */
    public Date getToopertime() {
        return toopertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.TOOPERTIME
     *
     * @param toopertime the value for db_tasklog.TOOPERTIME
     *
     * @mbg.generated
     */
    public void setToopertime(Date toopertime) {
        this.toopertime = toopertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.STATUS
     *
     * @return the value of db_tasklog.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.STATUS
     *
     * @param status the value for db_tasklog.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.STATUSNAME
     *
     * @return the value of db_tasklog.STATUSNAME
     *
     * @mbg.generated
     */
    public String getStatusname() {
        return statusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.STATUSNAME
     *
     * @param statusname the value for db_tasklog.STATUSNAME
     *
     * @mbg.generated
     */
    public void setStatusname(String statusname) {
        this.statusname = statusname == null ? null : statusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.SLEVEL
     *
     * @return the value of db_tasklog.SLEVEL
     *
     * @mbg.generated
     */
    public String getSlevel() {
        return slevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.SLEVEL
     *
     * @param slevel the value for db_tasklog.SLEVEL
     *
     * @mbg.generated
     */
    public void setSlevel(String slevel) {
        this.slevel = slevel == null ? null : slevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.CHECKRESULT
     *
     * @return the value of db_tasklog.CHECKRESULT
     *
     * @mbg.generated
     */
    public String getCheckresult() {
        return checkresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.CHECKRESULT
     *
     * @param checkresult the value for db_tasklog.CHECKRESULT
     *
     * @mbg.generated
     */
    public void setCheckresult(String checkresult) {
        this.checkresult = checkresult == null ? null : checkresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.SCORES
     *
     * @return the value of db_tasklog.SCORES
     *
     * @mbg.generated
     */
    public BigDecimal getScores() {
        return scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.SCORES
     *
     * @param scores the value for db_tasklog.SCORES
     *
     * @mbg.generated
     */
    public void setScores(BigDecimal scores) {
        this.scores = scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.CHECKOPER
     *
     * @return the value of db_tasklog.CHECKOPER
     *
     * @mbg.generated
     */
    public String getCheckoper() {
        return checkoper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.CHECKOPER
     *
     * @param checkoper the value for db_tasklog.CHECKOPER
     *
     * @mbg.generated
     */
    public void setCheckoper(String checkoper) {
        this.checkoper = checkoper == null ? null : checkoper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.CHECKTIME
     *
     * @return the value of db_tasklog.CHECKTIME
     *
     * @mbg.generated
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.CHECKTIME
     *
     * @param checktime the value for db_tasklog.CHECKTIME
     *
     * @mbg.generated
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.PUBLICFLAG
     *
     * @return the value of db_tasklog.PUBLICFLAG
     *
     * @mbg.generated
     */
    public String getPublicflag() {
        return publicflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.PUBLICFLAG
     *
     * @param publicflag the value for db_tasklog.PUBLICFLAG
     *
     * @mbg.generated
     */
    public void setPublicflag(String publicflag) {
        this.publicflag = publicflag == null ? null : publicflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.RESERVE1
     *
     * @return the value of db_tasklog.RESERVE1
     *
     * @mbg.generated
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.RESERVE1
     *
     * @param reserve1 the value for db_tasklog.RESERVE1
     *
     * @mbg.generated
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.RESERVE2
     *
     * @return the value of db_tasklog.RESERVE2
     *
     * @mbg.generated
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.RESERVE2
     *
     * @param reserve2 the value for db_tasklog.RESERVE2
     *
     * @mbg.generated
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.RESERVE3
     *
     * @return the value of db_tasklog.RESERVE3
     *
     * @mbg.generated
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.RESERVE3
     *
     * @param reserve3 the value for db_tasklog.RESERVE3
     *
     * @mbg.generated
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.RESERVE4
     *
     * @return the value of db_tasklog.RESERVE4
     *
     * @mbg.generated
     */
    public String getReserve4() {
        return reserve4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.RESERVE4
     *
     * @param reserve4 the value for db_tasklog.RESERVE4
     *
     * @mbg.generated
     */
    public void setReserve4(String reserve4) {
        this.reserve4 = reserve4 == null ? null : reserve4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.RESERVE5
     *
     * @return the value of db_tasklog.RESERVE5
     *
     * @mbg.generated
     */
    public String getReserve5() {
        return reserve5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.RESERVE5
     *
     * @param reserve5 the value for db_tasklog.RESERVE5
     *
     * @mbg.generated
     */
    public void setReserve5(String reserve5) {
        this.reserve5 = reserve5 == null ? null : reserve5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.ENDTIME
     *
     * @return the value of db_tasklog.ENDTIME
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.ENDTIME
     *
     * @param endtime the value for db_tasklog.ENDTIME
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.DATEDIFF
     *
     * @return the value of db_tasklog.DATEDIFF
     *
     * @mbg.generated
     */
    public BigDecimal getDatediff() {
        return datediff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.DATEDIFF
     *
     * @param datediff the value for db_tasklog.DATEDIFF
     *
     * @mbg.generated
     */
    public void setDatediff(BigDecimal datediff) {
        this.datediff = datediff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.CORPID
     *
     * @return the value of db_tasklog.CORPID
     *
     * @mbg.generated
     */
    public String getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.CORPID
     *
     * @param corpid the value for db_tasklog.CORPID
     *
     * @mbg.generated
     */
    public void setCorpid(String corpid) {
        this.corpid = corpid == null ? null : corpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.OPERTYPE
     *
     * @return the value of db_tasklog.OPERTYPE
     *
     * @mbg.generated
     */
    public String getOpertype() {
        return opertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.OPERTYPE
     *
     * @param opertype the value for db_tasklog.OPERTYPE
     *
     * @mbg.generated
     */
    public void setOpertype(String opertype) {
        this.opertype = opertype == null ? null : opertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.STATUSFLAG
     *
     * @return the value of db_tasklog.STATUSFLAG
     *
     * @mbg.generated
     */
    public String getStatusflag() {
        return statusflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.STATUSFLAG
     *
     * @param statusflag the value for db_tasklog.STATUSFLAG
     *
     * @mbg.generated
     */
    public void setStatusflag(String statusflag) {
        this.statusflag = statusflag == null ? null : statusflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.CUSTOMERTYPE
     *
     * @return the value of db_tasklog.CUSTOMERTYPE
     *
     * @mbg.generated
     */
    public String getCustomertype() {
        return customertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.CUSTOMERTYPE
     *
     * @param customertype the value for db_tasklog.CUSTOMERTYPE
     *
     * @mbg.generated
     */
    public void setCustomertype(String customertype) {
        this.customertype = customertype == null ? null : customertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.TITLE
     *
     * @return the value of db_tasklog.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.TITLE
     *
     * @param title the value for db_tasklog.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.QUESTION
     *
     * @return the value of db_tasklog.QUESTION
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.QUESTION
     *
     * @param question the value for db_tasklog.QUESTION
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.ANSWER
     *
     * @return the value of db_tasklog.ANSWER
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.ANSWER
     *
     * @param answer the value for db_tasklog.ANSWER
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.CHECKDESCR
     *
     * @return the value of db_tasklog.CHECKDESCR
     *
     * @mbg.generated
     */
    public String getCheckdescr() {
        return checkdescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.CHECKDESCR
     *
     * @param checkdescr the value for db_tasklog.CHECKDESCR
     *
     * @mbg.generated
     */
    public void setCheckdescr(String checkdescr) {
        this.checkdescr = checkdescr == null ? null : checkdescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.CONTENT
     *
     * @return the value of db_tasklog.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.CONTENT
     *
     * @param content the value for db_tasklog.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.MEMBER
     *
     * @return the value of db_tasklog.MEMBER
     *
     * @mbg.generated
     */
    public String getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.MEMBER
     *
     * @param member the value for db_tasklog.MEMBER
     *
     * @mbg.generated
     */
    public void setMember(String member) {
        this.member = member == null ? null : member.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_tasklog.CUSTOMERNAME
     *
     * @return the value of db_tasklog.CUSTOMERNAME
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_tasklog.CUSTOMERNAME
     *
     * @param customername the value for db_tasklog.CUSTOMERNAME
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_tasklog
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbTasklog other = (DbTasklog) that;
        return (this.getSequenceid() == null ? other.getSequenceid() == null : this.getSequenceid().equals(other.getSequenceid()))
            && (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
            && (this.getStype() == null ? other.getStype() == null : this.getStype().equals(other.getStype()))
            && (this.getStypename() == null ? other.getStypename() == null : this.getStypename().equals(other.getStypename()))
            && (this.getOper() == null ? other.getOper() == null : this.getOper().equals(other.getOper()))
            && (this.getOpertime() == null ? other.getOpertime() == null : this.getOpertime().equals(other.getOpertime()))
            && (this.getTooper() == null ? other.getTooper() == null : this.getTooper().equals(other.getTooper()))
            && (this.getToopertime() == null ? other.getToopertime() == null : this.getToopertime().equals(other.getToopertime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getStatusname() == null ? other.getStatusname() == null : this.getStatusname().equals(other.getStatusname()))
            && (this.getSlevel() == null ? other.getSlevel() == null : this.getSlevel().equals(other.getSlevel()))
            && (this.getCheckresult() == null ? other.getCheckresult() == null : this.getCheckresult().equals(other.getCheckresult()))
            && (this.getScores() == null ? other.getScores() == null : this.getScores().equals(other.getScores()))
            && (this.getCheckoper() == null ? other.getCheckoper() == null : this.getCheckoper().equals(other.getCheckoper()))
            && (this.getChecktime() == null ? other.getChecktime() == null : this.getChecktime().equals(other.getChecktime()))
            && (this.getPublicflag() == null ? other.getPublicflag() == null : this.getPublicflag().equals(other.getPublicflag()))
            && (this.getReserve1() == null ? other.getReserve1() == null : this.getReserve1().equals(other.getReserve1()))
            && (this.getReserve2() == null ? other.getReserve2() == null : this.getReserve2().equals(other.getReserve2()))
            && (this.getReserve3() == null ? other.getReserve3() == null : this.getReserve3().equals(other.getReserve3()))
            && (this.getReserve4() == null ? other.getReserve4() == null : this.getReserve4().equals(other.getReserve4()))
            && (this.getReserve5() == null ? other.getReserve5() == null : this.getReserve5().equals(other.getReserve5()))
            && (this.getEndtime() == null ? other.getEndtime() == null : this.getEndtime().equals(other.getEndtime()))
            && (this.getDatediff() == null ? other.getDatediff() == null : this.getDatediff().equals(other.getDatediff()))
            && (this.getCorpid() == null ? other.getCorpid() == null : this.getCorpid().equals(other.getCorpid()))
            && (this.getOpertype() == null ? other.getOpertype() == null : this.getOpertype().equals(other.getOpertype()))
            && (this.getStatusflag() == null ? other.getStatusflag() == null : this.getStatusflag().equals(other.getStatusflag()))
            && (this.getCustomertype() == null ? other.getCustomertype() == null : this.getCustomertype().equals(other.getCustomertype()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getQuestion() == null ? other.getQuestion() == null : this.getQuestion().equals(other.getQuestion()))
            && (this.getAnswer() == null ? other.getAnswer() == null : this.getAnswer().equals(other.getAnswer()))
            && (this.getCheckdescr() == null ? other.getCheckdescr() == null : this.getCheckdescr().equals(other.getCheckdescr()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getMember() == null ? other.getMember() == null : this.getMember().equals(other.getMember()))
            && (this.getCustomername() == null ? other.getCustomername() == null : this.getCustomername().equals(other.getCustomername()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_tasklog
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSequenceid() == null) ? 0 : getSequenceid().hashCode());
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getStype() == null) ? 0 : getStype().hashCode());
        result = prime * result + ((getStypename() == null) ? 0 : getStypename().hashCode());
        result = prime * result + ((getOper() == null) ? 0 : getOper().hashCode());
        result = prime * result + ((getOpertime() == null) ? 0 : getOpertime().hashCode());
        result = prime * result + ((getTooper() == null) ? 0 : getTooper().hashCode());
        result = prime * result + ((getToopertime() == null) ? 0 : getToopertime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getStatusname() == null) ? 0 : getStatusname().hashCode());
        result = prime * result + ((getSlevel() == null) ? 0 : getSlevel().hashCode());
        result = prime * result + ((getCheckresult() == null) ? 0 : getCheckresult().hashCode());
        result = prime * result + ((getScores() == null) ? 0 : getScores().hashCode());
        result = prime * result + ((getCheckoper() == null) ? 0 : getCheckoper().hashCode());
        result = prime * result + ((getChecktime() == null) ? 0 : getChecktime().hashCode());
        result = prime * result + ((getPublicflag() == null) ? 0 : getPublicflag().hashCode());
        result = prime * result + ((getReserve1() == null) ? 0 : getReserve1().hashCode());
        result = prime * result + ((getReserve2() == null) ? 0 : getReserve2().hashCode());
        result = prime * result + ((getReserve3() == null) ? 0 : getReserve3().hashCode());
        result = prime * result + ((getReserve4() == null) ? 0 : getReserve4().hashCode());
        result = prime * result + ((getReserve5() == null) ? 0 : getReserve5().hashCode());
        result = prime * result + ((getEndtime() == null) ? 0 : getEndtime().hashCode());
        result = prime * result + ((getDatediff() == null) ? 0 : getDatediff().hashCode());
        result = prime * result + ((getCorpid() == null) ? 0 : getCorpid().hashCode());
        result = prime * result + ((getOpertype() == null) ? 0 : getOpertype().hashCode());
        result = prime * result + ((getStatusflag() == null) ? 0 : getStatusflag().hashCode());
        result = prime * result + ((getCustomertype() == null) ? 0 : getCustomertype().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getQuestion() == null) ? 0 : getQuestion().hashCode());
        result = prime * result + ((getAnswer() == null) ? 0 : getAnswer().hashCode());
        result = prime * result + ((getCheckdescr() == null) ? 0 : getCheckdescr().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getMember() == null) ? 0 : getMember().hashCode());
        result = prime * result + ((getCustomername() == null) ? 0 : getCustomername().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_tasklog
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sequenceid=").append(sequenceid);
        sb.append(", sid=").append(sid);
        sb.append(", stype=").append(stype);
        sb.append(", stypename=").append(stypename);
        sb.append(", oper=").append(oper);
        sb.append(", opertime=").append(opertime);
        sb.append(", tooper=").append(tooper);
        sb.append(", toopertime=").append(toopertime);
        sb.append(", status=").append(status);
        sb.append(", statusname=").append(statusname);
        sb.append(", slevel=").append(slevel);
        sb.append(", checkresult=").append(checkresult);
        sb.append(", scores=").append(scores);
        sb.append(", checkoper=").append(checkoper);
        sb.append(", checktime=").append(checktime);
        sb.append(", publicflag=").append(publicflag);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", reserve3=").append(reserve3);
        sb.append(", reserve4=").append(reserve4);
        sb.append(", reserve5=").append(reserve5);
        sb.append(", endtime=").append(endtime);
        sb.append(", datediff=").append(datediff);
        sb.append(", corpid=").append(corpid);
        sb.append(", opertype=").append(opertype);
        sb.append(", statusflag=").append(statusflag);
        sb.append(", customertype=").append(customertype);
        sb.append(", title=").append(title);
        sb.append(", question=").append(question);
        sb.append(", answer=").append(answer);
        sb.append(", checkdescr=").append(checkdescr);
        sb.append(", content=").append(content);
        sb.append(", member=").append(member);
        sb.append(", customername=").append(customername);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}