package com.bean.dao;

import com.bean.model.DbAlifeedbackorder;
import java.util.List;

public interface DbAlifeedbackorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alifeedbackorder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alifeedbackorder
     *
     * @mbg.generated
     */
    int insert(DbAlifeedbackorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alifeedbackorder
     *
     * @mbg.generated
     */
    DbAlifeedbackorder selectByPrimaryKey(String tradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alifeedbackorder
     *
     * @mbg.generated
     */
    List<DbAlifeedbackorder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alifeedbackorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbAlifeedbackorder record);
}