package com.bean.dao;

import com.bean.model.DbAlisku;
import java.util.List;

public interface DbAliskuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alisku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String skuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alisku
     *
     * @mbg.generated
     */
    int insert(DbAlisku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alisku
     *
     * @mbg.generated
     */
    DbAlisku selectByPrimaryKey(String skuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alisku
     *
     * @mbg.generated
     */
    List<DbAlisku> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_alisku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbAlisku record);
}