package com.bean.dao;

import com.bean.model.DbAnalysetype;
import java.util.List;

public interface DbAnalysetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_analysetype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_analysetype
     *
     * @mbg.generated
     */
    int insert(DbAnalysetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_analysetype
     *
     * @mbg.generated
     */
    DbAnalysetype selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_analysetype
     *
     * @mbg.generated
     */
    List<DbAnalysetype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_analysetype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbAnalysetype record);
}