package com.bean.dao;

import com.bean.model.DbBirdexpresstype;
import java.util.List;

public interface DbBirdexpresstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdexpresstype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdexpresstype
     *
     * @mbg.generated
     */
    int insert(DbBirdexpresstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdexpresstype
     *
     * @mbg.generated
     */
    DbBirdexpresstype selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdexpresstype
     *
     * @mbg.generated
     */
    List<DbBirdexpresstype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_birdexpresstype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbBirdexpresstype record);
}