package com.bean.dao;

import com.bean.model.DbBiaojuuser;
import java.util.List;

public interface DbBiaojuuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_biaojuuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_biaojuuser
     *
     * @mbg.generated
     */
    int insert(DbBiaojuuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_biaojuuser
     *
     * @mbg.generated
     */
    DbBiaojuuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_biaojuuser
     *
     * @mbg.generated
     */
    List<DbBiaojuuser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_biaojuuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbBiaojuuser record);
}