package com.bean.dao;

import com.bean.model.DbBpostseller;
import java.math.BigDecimal;
import java.util.List;

public interface DbBpostsellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostseller
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostseller
     *
     * @mbg.generated
     */
    int insert(DbBpostseller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostseller
     *
     * @mbg.generated
     */
    DbBpostseller selectByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostseller
     *
     * @mbg.generated
     */
    List<DbBpostseller> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostseller
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbBpostseller record);
}