package com.bean.dao;

import com.bean.model.DbBpostexpresstype;
import java.util.List;

public interface DbBpostexpresstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostexpresstype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostexpresstype
     *
     * @mbg.generated
     */
    int insert(DbBpostexpresstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostexpresstype
     *
     * @mbg.generated
     */
    DbBpostexpresstype selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostexpresstype
     *
     * @mbg.generated
     */
    List<DbBpostexpresstype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bpostexpresstype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbBpostexpresstype record);
}