package com.bean.dao;

import com.bean.model.DbCountry;
import java.util.List;

public interface DbCountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_country
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String countryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_country
     *
     * @mbg.generated
     */
    int insert(DbCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_country
     *
     * @mbg.generated
     */
    DbCountry selectByPrimaryKey(String countryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_country
     *
     * @mbg.generated
     */
    List<DbCountry> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_country
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbCountry record);
}