package com.bean.dao;

import com.bean.model.DbDescraption;
import java.math.BigDecimal;
import java.util.List;

public interface DbDescraptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_descraption
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_descraption
     *
     * @mbg.generated
     */
    int insert(DbDescraption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_descraption
     *
     * @mbg.generated
     */
    DbDescraption selectByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_descraption
     *
     * @mbg.generated
     */
    List<DbDescraption> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_descraption
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbDescraption record);
}