package com.bean.dao;

import com.bean.model.DbDownloadcount;
import java.util.List;

public interface DbDownloadcountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_downloadcount
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_downloadcount
     *
     * @mbg.generated
     */
    int insert(DbDownloadcount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_downloadcount
     *
     * @mbg.generated
     */
    DbDownloadcount selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_downloadcount
     *
     * @mbg.generated
     */
    List<DbDownloadcount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_downloadcount
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbDownloadcount record);
}