package com.bean.dao;

import com.bean.model.DbEbaylimit;
import java.math.BigDecimal;
import java.util.List;

public interface DbEbaylimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaylimit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaylimit
     *
     * @mbg.generated
     */
    int insert(DbEbaylimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaylimit
     *
     * @mbg.generated
     */
    DbEbaylimit selectByPrimaryKey(BigDecimal sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaylimit
     *
     * @mbg.generated
     */
    List<DbEbaylimit> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaylimit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbEbaylimit record);
}