package com.bean.dao;

import com.bean.model.DbEbayforexpress;
import java.util.List;

public interface DbEbayforexpressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebayforexpress
     *
     * @mbg.generated
     */
    int insert(DbEbayforexpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebayforexpress
     *
     * @mbg.generated
     */
    List<DbEbayforexpress> selectAll();
}