package com.bean.dao;

import com.bean.model.DbEbaytotalsales;
import java.math.BigDecimal;
import java.util.List;

public interface DbEbaytotalsalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaytotalsales
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaytotalsales
     *
     * @mbg.generated
     */
    int insert(DbEbaytotalsales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaytotalsales
     *
     * @mbg.generated
     */
    DbEbaytotalsales selectByPrimaryKey(BigDecimal sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaytotalsales
     *
     * @mbg.generated
     */
    List<DbEbaytotalsales> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ebaytotalsales
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbEbaytotalsales record);
}