package com.bean.dao;

import com.bean.model.DbExpensetype;
import java.util.List;

public interface DbExpensetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expensetype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expensetype
     *
     * @mbg.generated
     */
    int insert(DbExpensetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expensetype
     *
     * @mbg.generated
     */
    DbExpensetype selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expensetype
     *
     * @mbg.generated
     */
    List<DbExpensetype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expensetype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbExpensetype record);
}