package com.bean.dao;

import com.bean.model.DbExpresstyperule;
import java.math.BigDecimal;
import java.util.List;

public interface DbExpresstyperuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expresstyperule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expresstyperule
     *
     * @mbg.generated
     */
    int insert(DbExpresstyperule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expresstyperule
     *
     * @mbg.generated
     */
    DbExpresstyperule selectByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expresstyperule
     *
     * @mbg.generated
     */
    List<DbExpresstyperule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_expresstyperule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbExpresstyperule record);
}