package com.bean.dao;

import com.bean.model.DbFpxoriginarea;
import java.util.List;

public interface DbFpxoriginareaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_fpxoriginarea
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_fpxoriginarea
     *
     * @mbg.generated
     */
    int insert(DbFpxoriginarea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_fpxoriginarea
     *
     * @mbg.generated
     */
    DbFpxoriginarea selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_fpxoriginarea
     *
     * @mbg.generated
     */
    List<DbFpxoriginarea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_fpxoriginarea
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbFpxoriginarea record);
}