package com.bean.dao;

import com.bean.model.DbItemspe;
import java.util.List;

public interface DbItemspeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemspe
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemspe
     *
     * @mbg.generated
     */
    int insert(DbItemspe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemspe
     *
     * @mbg.generated
     */
    DbItemspe selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemspe
     *
     * @mbg.generated
     */
    List<DbItemspe> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemspe
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbItemspe record);
}