package com.bean.dao;

import com.bean.model.DbItemscontent;
import java.util.List;

public interface DbItemscontentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemscontent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemscontent
     *
     * @mbg.generated
     */
    int insert(DbItemscontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemscontent
     *
     * @mbg.generated
     */
    DbItemscontent selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemscontent
     *
     * @mbg.generated
     */
    List<DbItemscontent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_itemscontent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbItemscontent record);
}