package com.bean.dao;

import com.bean.model.DbLocation;
import java.util.List;

public interface DbLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_location
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_location
     *
     * @mbg.generated
     */
    int insert(DbLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_location
     *
     * @mbg.generated
     */
    DbLocation selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_location
     *
     * @mbg.generated
     */
    List<DbLocation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_location
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbLocation record);
}