package com.bean.dao;

import com.bean.model.DbMatecategory;
import java.math.BigDecimal;
import java.util.List;

public interface DbMatecategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_matecategory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_matecategory
     *
     * @mbg.generated
     */
    int insert(DbMatecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_matecategory
     *
     * @mbg.generated
     */
    DbMatecategory selectByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_matecategory
     *
     * @mbg.generated
     */
    List<DbMatecategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_matecategory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbMatecategory record);
}