package com.bean.dao;

import com.bean.model.DbNewitemresult;
import java.util.List;

public interface DbNewitemresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_newitemresult
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_newitemresult
     *
     * @mbg.generated
     */
    int insert(DbNewitemresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_newitemresult
     *
     * @mbg.generated
     */
    DbNewitemresult selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_newitemresult
     *
     * @mbg.generated
     */
    List<DbNewitemresult> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_newitemresult
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbNewitemresult record);
}