package com.bean.dao;

import com.bean.model.DbNotonlineproduct;
import java.util.List;

public interface DbNotonlineproductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notonlineproduct
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notonlineproduct
     *
     * @mbg.generated
     */
    int insert(DbNotonlineproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notonlineproduct
     *
     * @mbg.generated
     */
    DbNotonlineproduct selectByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notonlineproduct
     *
     * @mbg.generated
     */
    List<DbNotonlineproduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notonlineproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbNotonlineproduct record);
}