package com.bean.dao;

import com.bean.model.DbOrdertypelog;
import java.util.List;

public interface DbOrdertypelogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ordertypelog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ordertypelog
     *
     * @mbg.generated
     */
    int insert(DbOrdertypelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ordertypelog
     *
     * @mbg.generated
     */
    DbOrdertypelog selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ordertypelog
     *
     * @mbg.generated
     */
    List<DbOrdertypelog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ordertypelog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbOrdertypelog record);
}