package com.bean.dao;

import com.bean.model.DbOrderHistoryLog;
import java.util.List;

public interface DbOrderHistoryLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_order_history_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_order_history_log
     *
     * @mbg.generated
     */
    int insert(DbOrderHistoryLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_order_history_log
     *
     * @mbg.generated
     */
    DbOrderHistoryLog selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_order_history_log
     *
     * @mbg.generated
     */
    List<DbOrderHistoryLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_order_history_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbOrderHistoryLog record);
}