package com.bean.dao;

import com.bean.model.DbPaymentmethodTemp;
import java.math.BigDecimal;
import java.util.List;

public interface DbPaymentmethodTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_paymentmethod_temp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_paymentmethod_temp
     *
     * @mbg.generated
     */
    int insert(DbPaymentmethodTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_paymentmethod_temp
     *
     * @mbg.generated
     */
    DbPaymentmethodTemp selectByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_paymentmethod_temp
     *
     * @mbg.generated
     */
    List<DbPaymentmethodTemp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_paymentmethod_temp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbPaymentmethodTemp record);
}