package com.bean.dao;

import com.bean.model.DbProductOnlineTemp;
import java.util.List;

public interface DbProductOnlineTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_product_online_temp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_product_online_temp
     *
     * @mbg.generated
     */
    int insert(DbProductOnlineTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_product_online_temp
     *
     * @mbg.generated
     */
    DbProductOnlineTemp selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_product_online_temp
     *
     * @mbg.generated
     */
    List<DbProductOnlineTemp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_product_online_temp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbProductOnlineTemp record);
}