package com.bean.dao;

import com.bean.model.DbProductbackinfo;
import java.util.List;

public interface DbProductbackinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_productbackinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_productbackinfo
     *
     * @mbg.generated
     */
    int insert(DbProductbackinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_productbackinfo
     *
     * @mbg.generated
     */
    DbProductbackinfo selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_productbackinfo
     *
     * @mbg.generated
     */
    List<DbProductbackinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_productbackinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbProductbackinfo record);
}