package com.bean.dao;

import com.bean.model.DbQtsku;
import java.util.List;

public interface DbQtskuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_qtsku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String qtsku);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_qtsku
     *
     * @mbg.generated
     */
    int insert(DbQtsku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_qtsku
     *
     * @mbg.generated
     */
    DbQtsku selectByPrimaryKey(String qtsku);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_qtsku
     *
     * @mbg.generated
     */
    List<DbQtsku> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_qtsku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbQtsku record);
}