package com.bean.dao;

import com.bean.model.DbSavenummonth;
import java.util.List;

public interface DbSavenummonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_savenummonth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String month);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_savenummonth
     *
     * @mbg.generated
     */
    int insert(DbSavenummonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_savenummonth
     *
     * @mbg.generated
     */
    DbSavenummonth selectByPrimaryKey(String month);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_savenummonth
     *
     * @mbg.generated
     */
    List<DbSavenummonth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_savenummonth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbSavenummonth record);
}