package com.bean.dao;

import com.bean.model.DbSendmessage;
import java.util.List;

public interface DbSendmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sendmessage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sendmessage
     *
     * @mbg.generated
     */
    int insert(DbSendmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sendmessage
     *
     * @mbg.generated
     */
    DbSendmessage selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sendmessage
     *
     * @mbg.generated
     */
    List<DbSendmessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_sendmessage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbSendmessage record);
}