package com.bean.dao;

import com.bean.model.DbShopifyproduct;
import java.util.List;

public interface DbShopifyproductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_shopifyproduct
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String variantid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_shopifyproduct
     *
     * @mbg.generated
     */
    int insert(DbShopifyproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_shopifyproduct
     *
     * @mbg.generated
     */
    DbShopifyproduct selectByPrimaryKey(String variantid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_shopifyproduct
     *
     * @mbg.generated
     */
    List<DbShopifyproduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_shopifyproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbShopifyproduct record);
}