package com.bean.dao;

import com.bean.model.DbSmtaddress;
import java.util.List;

public interface DbSmtaddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smtaddress
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smtaddress
     *
     * @mbg.generated
     */
    int insert(DbSmtaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smtaddress
     *
     * @mbg.generated
     */
    DbSmtaddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smtaddress
     *
     * @mbg.generated
     */
    List<DbSmtaddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smtaddress
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbSmtaddress record);
}