package com.bean.dao;

import com.bean.model.DbSmsprompt;
import java.util.List;

public interface DbSmspromptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smsprompt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smsprompt
     *
     * @mbg.generated
     */
    int insert(DbSmsprompt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smsprompt
     *
     * @mbg.generated
     */
    DbSmsprompt selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smsprompt
     *
     * @mbg.generated
     */
    List<DbSmsprompt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_smsprompt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbSmsprompt record);
}