package com.bean.dao;

import com.bean.model.DbStorage;
import java.util.List;

public interface DbStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_storage
     *
     * @mbg.generated
     */
    int insert(DbStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_storage
     *
     * @mbg.generated
     */
    DbStorage selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_storage
     *
     * @mbg.generated
     */
    List<DbStorage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbStorage record);
}