package com.bean.dao;

import com.bean.model.DbTaskstatuslog;
import java.util.List;

public interface DbTaskstatuslogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_taskstatuslog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_taskstatuslog
     *
     * @mbg.generated
     */
    int insert(DbTaskstatuslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_taskstatuslog
     *
     * @mbg.generated
     */
    DbTaskstatuslog selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_taskstatuslog
     *
     * @mbg.generated
     */
    List<DbTaskstatuslog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_taskstatuslog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbTaskstatuslog record);
}