package com.bean.dao;

import com.bean.model.DbTwodevelopmentproductlog;
import java.util.List;

public interface DbTwodevelopmentproductlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_twodevelopmentproductlog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_twodevelopmentproductlog
     *
     * @mbg.generated
     */
    int insert(DbTwodevelopmentproductlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_twodevelopmentproductlog
     *
     * @mbg.generated
     */
    DbTwodevelopmentproductlog selectByPrimaryKey(String sequenceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_twodevelopmentproductlog
     *
     * @mbg.generated
     */
    List<DbTwodevelopmentproductlog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_twodevelopmentproductlog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbTwodevelopmentproductlog record);
}