package com.bean.dao;

import com.bean.model.DbYwuser;
import java.util.List;

public interface DbYwuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ywuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ywuser
     *
     * @mbg.generated
     */
    int insert(DbYwuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ywuser
     *
     * @mbg.generated
     */
    DbYwuser selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ywuser
     *
     * @mbg.generated
     */
    List<DbYwuser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_ywuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbYwuser record);
}