package com.bean.dao;

import com.bean.model.StatProductShopDaily;
import java.util.List;

public interface StatProductShopDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_product_shop_daily
     *
     * @mbg.generated
     */
    int insert(StatProductShopDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_product_shop_daily
     *
     * @mbg.generated
     */
    List<StatProductShopDaily> selectAll();
}