server:
  port: 8066
  servlet:
    context-path: /pro
spring:
  datasource:
    name: bean
    url: jdbc:mysql://127.0.0.1:3306/shop
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10
  application:
    name: kafka-user
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8         # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1ms        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8           # 连接池中的最大空闲连接 默认 8
        min-idle: 0           # 连接池中的最小空闲连接 默认 0
    timeout: 5000


queueName: publish.queue
topicName: publish.topic
queue2Name: publish.que