server:
  port: 8082
  tomcat:
    uri-encoding: utf-8

spring:
    datasource:
        name: bean
        url: jdbc:mysql://127.0.0.1:3306/db1
        username: sh1
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
    session:
      store-type: none


logging:
  path: log/logging.log
  level:
    com.xxx: debug
mybatis:
  type-aliases-package: com.bean.model
  mapper-locations: mapping/*.xml

#前缀首字母小写，多单词‘-’分隔
is-open:
    lazadaFlag: 1









lazada:
    appkey: 1
    secret: 1
    fershHost: 1
    skuPosition: 1
    multiFlag: 1
    holdSpace: false
    platformFeeRate: 0.01



